---
- hosts: web
  tasks:
    - name: Add Nginx Repository
      apt_repository: 
        repo: ppa:nginx/stable
      register: ppastable

    - name: Install Nginx
      apt: pkg=nginx state=present update_cache=true
      when: ppastable is success
      register: nginxinstalled
      notify:
        - Start Nginx

    - name: Disable Default Site
      when: nginxinstalled is success
      file:
        dest: /etc/nginx/sites-enabled/default
        state: absent
    
    - name: Add Sandbox Site Config
      when: nginxinstalled is success
      register: sandboxconfig
      template: 
        src: sandbox.local.j2
        dest: /etc/nginx/sites-available/'{{ docroot }}'

    - name: Create Web Root
      when: nginxinstalled is success
      file: dest={{ '{{' }} docroot {{ '}}' }} mode=775 state=directory owner=www-data group=www-data
      notify:
        - Reload Nginx

    - name: Web Root Permissions
      when: nginxisinstalled is success
      file:
        dest: /var/www/'{{ domain }}'/public
        mode: 775
        state: directory
        owner: www-data
        group: www-data
      notify:
        - Reload Nginx

  handlers:
    - name: Start Nginx
      service: name=nginx state=started

    - name: Reload Nginx
      service: name=nginx state=reloaded
